name: "{{ home_name }}-vaultwarden"
services:
  vaultwarden:
    container_name: "{{ home_name }}-vaultwarden"
    image: vaultwarden/server:latest
    environment:
      TZ: "{{ home_timezone }}"
    volumes:
      - vaultwarden_data:/data
    restart: always
    ports:
      - "{{ vaultwarden_bind_host }}:{{ vaultwarden_bind_port }}:80"
    logging: {{ vaultwarden.logging.vaultwarden }}
networks: {}
volumes:
  vaultwarden_data: {{ vaultwarden.volumes.vaultwarden_data }}