name: "{{ home_name }}-aria2"
services:
  aria2:
    container_name: "{{ home_name }}-aria2"
    image: "{{ home_images.aria2 }}"
    environment:
      UMASK_SET: 022
      RPC_SECRET: "{{ home_secrets.aria2.rpc_secret }}"
      RPC_PORT: 6800
      LISTEN_PORT: 6888
      DISK_CACHE: 64M
      IPV6_MODE: false
      UPDATE_TRACKERS: true
      CUSTOM_TRACKER_URL: 
      TZ: "{{ home_timezone }}"
      PUID: "{{ home_uid }}"
      PGID: "{{ home_gid }}"
    volumes:
      - aria2-config:/config
      - aria2-downloads:/downloads
    ports:
      - "{{ aria2_rpc_bind_host }}:{{ aria2_rpc_bind_port }}:6800"
      - 6888:6888
      - 6888:6888/udp
    logging: {{ service_vars.logging.aria2 }}
    restart: unless-stopped

  aria-ng:
    container_name: "{{ home_name }}-aria-ng"
    image: p3terx/ariang
    command: --port 6801 --ipv6
    ports:
      - "{{ aria_ng_bind_host }}:{{ aria_ng_bind_port }}:6801"
    restart: unless-stopped
    logging: {{ service_vars.logging.aria_ng }}

networks: {}

volumes:
  aria2-config: {{ service_vars.volumes.aria2_config }}
  aria2-downloads: {{ service_vars.volumes.aria2_downloads }}