name: mosdns
services:
  mosdns:
    image: "{{ home_images.mosdns }}"
    container_name: "{{ home_name }}-mosdns"
    restart: unless-stopped
    environment:
      TZ: "{{ home_timezone }}"
    volumes:
      - "{{ push_target_dir }}/config.yml:/etc/mosdns/config.yml:ro"
    network_mode: host
    logging: {{ service_vars.logging.mosdns }}

networks: {}