name: "{{ home_name }}-mosdns"
services:
  mosdns:
    image: "{{ home_images.mosdns.image }}"
    container_name: "{{ home_name }}-mosdns"
    restart: always
    environment:
      TZ: "{{ home_timezone }}"
    volumes:
      - "{{ push_target_dir }}/config.yml:/etc/mosdns/config.yml:ro"
    logging: {{ service_vars.logging.mosdns }}
    ports:
      - "{{ mosdns_udp_bind_host }}:{{ mosdns_udp_bind_port }}:53/udp"
      - "{{ mosdns_tcp_bind_host }}:{{ mosdns_tcp_bind_port }}:53/tcp"
      - "{{ mosdns_api_bind_host }}:{{ mosdns_api_bind_port }}:80"

networks: {}