home_name: zzq_home
home_user: "{{ home_name }}_service"
home_group: "{{ home_name }}_service"
home_uid: 100000
home_gid: 100000
home_timezone: Asia/Shanghai

home_services_dir: /home/{{ home_user }}/services # 服务配置路径
home_volumes_dir: /home/{{ home_user }}/volumes # 持久化卷路径

home_base_domain: "i.zhangzqs.cn"
home_http_enabled: true
home_https_enabled: true
