conf:

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: "{{ home_volumes_dir }}/{{ service }}/grafana_data"
      o: bind

precreate_dirs:
  - path: "{{ home_volumes_dir }}/{{ service }}"
    mode: 0755
    owner: "{{ home_uid }}"
    group: "{{ home_gid }}"

  - path: "{{ home_volumes_dir }}/{{ service }}/grafana_data"
    mode: 0755
    owner: 472
    group: 0

logging:
  grafana: "{{ home_default_logging }}"