logging:
  mosdns: "{{ home_default_logging }}"

conf:
  custom_domains:
    # Samba 共享域名
    - "smb.{{ home_base_domain }} 192.168.242.2"
    # Nginx 泛域名解析
    - "{{ home_base_domain }} 192.168.242.2"
    - "domain:{{ home_base_domain }} 192.168.242.2"
