conf:
  mihome_devices: []

precreate_dirs:
  - path: "{{ home_volumes_dir }}/{{ service }}"
    mode: 0755
    owner: "{{ home_uid }}"
    group: "{{ home_gid }}"
  - path: "{{ home_volumes_dir }}/{{ service }}/data"
    mode: 0755
    owner: "{{ home_uid }}"
    group: "{{ home_gid }}"
volumes:
  my_exporter_data:
    driver: local
    driver_opts:
      type: none
      device: "{{ home_volumes_dir }}/{{ service }}/data"
      o: bind
