conf:
  services_domains: # 各个服务的各个域名配置列表
    portainer:
      - domain: "portainer.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    vaultwarden:
      - domain: "vaultwarden.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    prometheus:
      - domain: "prometheus.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    grafana:
      - domain: "grafana.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    speedtest:
      - domain: "speedtest.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    drawio:
      - domain: "drawio.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    aria2:
      - domain: "aria2.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    immich:
      - domain: "immich.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    plantuml:
      - domain: "plantuml.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    gitea:
      - domain: "gitea.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    kms:
      - domain: "kms.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    homepage:
      - domain: "homepage.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    dify:
      - domain: "dify.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    rclone_webdav:
      - domain: "rclone-webdav.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    filebrowser:
      - domain: "filebrowser.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
    it_tools:
      - domain: "it-tools.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
  custom_services:
    upstreams:
      - name: "pve_nodes"
        addresses:
          - server: "192.168.242.3:8006"
            max_fails: 3
      - name: "codeserver_nodes"
        addresses:
          - server: "192.168.242.2:8091"
            max_fails: 3
    servers:
      - domain: "pve.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
        route_conf:
          - location: "/"
            proxy_pass: "https://pve_nodes"
      - domain: "codeserver.{{ home_base_domain }}"
        http_enabled: "{{ home_http_enabled }}"
        https_enabled: "{{ home_https_enabled }}"
        route_conf:
          - location: "/"
            proxy_pass: "http://codeserver_nodes"
          - location: "/api/v1/"
            proxy_pass: "http://codeserver_nodes"
          - location: "/static/"
            proxy_pass: "http://codeserver_nodes"

precreate_dirs:
  - path: "{{ home_volumes_dir }}/{{ service }}"
    mode: 0755
    owner: "{{ home_uid }}"
    group: "{{ home_gid }}"

  - path: "{{ home_volumes_dir }}/{{ service }}/logs"
    mode: 0755
    owner: 0
    group: 0

  - path: "{{ home_volumes_dir }}/{{ service }}/cache"
    mode: 0755
    owner: 0
    group: 0

logging:
  nginx: "{{ home_default_logging }}"

volumes:
  nginx_logs:
    driver: local
    driver_opts:
      type: none
      device: "{{ home_volumes_dir }}/{{ service }}/logs"
      o: bind

  nginx_cache:
    driver: local
    driver_opts:
      type: none
      device: "{{ home_volumes_dir }}/{{ service }}/cache"
      o: bind
