all:
  hosts:
    localhost: # 用于在Ansible控制机上执行一些任务时使用
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    my-j1900: # 我的j1900工控机
      ansible_host: "192.168.242.2"
      ansible_user: "root"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "inventory/default/ssh_key/id_ed25519"

      service_bind_host: "192.168.242.2" # 这上面的所有服务绑定到这个地址
  children:
    fluentd: # 每一台机器上各部署一个fluentd
      hosts:
        my-j1900: {}
      vars:
        fluentd_bind_host: "127.0.0.1"
        fluentd_bind_port: 24224
    node_exporter: # 每一台机器上各部署一个node_exporter
      hosts:
        my-j1900: {}
      vars: 
        node_exporter_bind_host: "{{ service_bind_host }}"
        node_exporter_bind_port: 9100
    cadvisor: # 每一台机器上各部署一个cadvisor
      hosts:
        my-j1900: {}
      vars:
        cadvisor_bind_host: "{{ service_bind_host }}"
        cadvisor_bind_port: 8080
    mosdns:
      hosts:
        my-j1900: {}
      vars:
        mosdns_api_bind_host: "{{ service_bind_host }}"
        mosdns_api_bind_port: 53
        mosdns_tcp_bind_host: "0.0.0.0"
        mosdns_tcp_bind_port: 531
        mosdns_udp_bind_host: "0.0.0.0"
        mosdns_udp_bind_port: 53
    prometheus: # 单节点部署
      hosts:
        my-j1900: {}
      vars:
        prometheus_bind_host: "{{ service_bind_host }}"
        prometheus_bind_port: 9090
    grafana: # 单节点部署
      hosts:
        my-j1900: {}
      vars:
        grafana_bind_host: "{{ service_bind_host }}"
        grafana_bind_port: 3000
    vaultwarden: 
      hosts:
        my-j1900: {}
      vars:
        vaultwarden_bind_host: "{{ service_bind_host }}"
        vaultwarden_bind_port: 8081
    portainer: # 单节点部署
      hosts:
        my-j1900: {}
      vars:
        portainer_bind_host: "{{ service_bind_host }}"
        portainer_bind_port: 9000
        portainer_https_bind_host: "{{ service_bind_host }}"
        portainer_https_bind_port: 9443
    nginx: # 单节点部署
      hosts:
        my-j1900: {}
    speedtest:
      hosts:
        my-j1900: {}
      vars:
        speedtest_bind_host: "{{ service_bind_host }}"
        speedtest_bind_port: 8082
    drawio:
      hosts:
        my-j1900: {}
      vars:
        drawio_bind_host: "{{ service_bind_host }}"
        drawio_bind_port: 8083