# 这里面放的都是固定变量

dpkg_architecture_map:
  x86_64: "amd64"

# Docker安装基础配置
# 官方源国内用不了，换成阿里源
# docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_gpg_url: https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
docker_gpg_key_path: /etc/apt/keyrings/docker.asc
docker_repo_path: /etc/apt/sources.list.d/docker.list
docker_repo_url: "https://mirrors.aliyun.com/docker-ce/linux/ubuntu"

# Docker守护进程配置
docker_daemon_config:
  default-ulimits:
    nofile:
      Name: "nofile"
      Hard: 65535
      Soft: 65535
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  storage-driver: "overlay2"
