---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: "{{ service_vars.conf.title }}"

background: "{{ service_vars.conf.background }}"

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

# hideVersion: true