name: "{{ home_name }}-mihome-exporter"
services:
  mihome_exporter:
    image: "{{ home_images.mihome_exporter.image }}"
    container_name: "{{ home_name }}-mihome-exporter"
    restart: always
    ports:
      - "{{ mihome_exporter_bind_host }}:{{ mihome_exporter_bind_port }}:8000/tcp"
    environment:
      TZ: "{{ home_timezone }}"
    command:
      - "uv"
      - "run" 
      - "src/main.py"
      - "--config=/config.yaml"
    
    volumes:
      - "{{ push_target_dir }}/config.yaml:/config.yaml:ro"
      - mihome_exporter_data:/data
networks: {}
volumes:
  mihome_exporter_data: {{ service_vars.volumes.mihome_exporter_data }}