name: "{{ home_name }}-grafana"
services:
  grafana:
    container_name: "{{ home_name }}-grafana"
    image: "{{ home_images.grafana.image }}"
    volumes:
      - "{{ push_target_dir }}/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "{{ push_target_dir }}/conf/provisioning:/provisioning_conf:ro"
      - "grafana_data:/var/lib/grafana"
    restart: always
    environment:
      TZ: "{{ home_timezone }}"
    logging: {{ grafana.logging.grafana }}
    ports:
      - "{{ grafana_bind_host }}:{{ grafana_bind_port }}:3000"

networks: {}

volumes:
  grafana_data: {{ grafana.volumes.grafana_data }}