name: "{{ home_name }}-homepage"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: "{{ home_name }}-homepage"
    ports:
      - "{{ homepage_bind_host }}:{{ homepage_bind_port }}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ push_target_dir }}/config:/app/config"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    environment:
      TZ: "{{ home_timezone }}"
      HOMEPAGE_ALLOWED_HOSTS: "*"
      LOG_TARGETS: stdout
networks: {}
