name: "{{ home_name }}-nginx"
services:
  nginx:
    image: "{{ home_images.nginx }}"
    container_name: "{{ home_name }}-nginx"
    restart: unless-stopped
    network_mode: host
    user: "0:0"
    environment:
      TZ: "{{ home_timezone }}"
    logging: {{ service_vars.logging.nginx }}
    volumes:
      - "{{ push_target_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ push_target_dir }}/conf.d:/etc/nginx/conf.d:ro"
      - "nginx_logs:/var/log/nginx"
      - "nginx_cache:/var/cache/nginx"
    ulimits:
      nofile:
        soft: 102400
        hard: 102400

networks: {}

volumes:
  nginx_logs: {{ service_vars.volumes.nginx_logs }}
  nginx_cache: {{ service_vars.volumes.nginx_cache }}