name: "{{ home_name }}-nginx"
services:
  nginx:
    image: "{{ home_images.nginx.image }}"
    container_name: "{{ home_name }}-nginx"
    restart: always
    network_mode: host
    user: "0:0"
    environment:
      TZ: "{{ home_timezone }}"
    logging: {{ service_vars.logging.nginx }}
    volumes:
      - "{{ push_target_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ push_target_dir }}/conf.d:/etc/nginx/conf.d:ro"
      - "{{ push_target_dir }}/sslcerts:/etc/nginx/ssl:ro"
      - "nginx_logs:/var/log/nginx"
      - "nginx_cache:/var/cache/nginx"
    ulimits:
      nofile:
        soft: 102400
        hard: 102400

  nginx_vts_exporter:
    image: "{{ home_images.nginx_vts_exporter.image }}"
    container_name: "{{ home_name }}-nginx-vts-exporter"
    restart: always
    network_mode: host
    user: "0:0"
    environment:
      TZ: "{{ home_timezone }}"
      NGINX_STATUS: "http://localhost/status/format/json"
      METRICS_ADDR: "{{ nginx_vts_exporter_bind_host }}:{{ nginx_vts_exporter_bind_port }}"

networks: {}

volumes:
  nginx_logs: {{ service_vars.volumes.nginx_logs }}
  nginx_cache: {{ service_vars.volumes.nginx_cache }}