name: "{{ home_name }}-speedtest"
services:
  speedtest:
    image: "{{ home_images.speedtest.image }}"
    container_name: "{{ home_name }}-speedtest"
    environment:
      TZ: "{{ home_timezone }}"
    restart: always
    ports:
      - "{{ speedtest_bind_host }}:{{ speedtest_bind_port }}:80"

networks: {}