apiVersion: 1
deleteDatasources:
   - name: Prometheus
     orgId: 1

datasources:
 - name: Prometheus-{{ home_name }}
   type: prometheus
   orgId: 1
   url: {{ groups.prometheus[0] }}:{{ prometheus_bind_port }}
   isDefault: true
   editable: true
