name: "{{ home_name }}-drawio"
services:
  drawio:
    image: "{{ home_images.drawio.image }}"
    container_name: "{{ home_name }}-drawio"
    environment:
      TZ: "{{ home_timezone }}"
    restart: always
    ports:
      - "{{ drawio_bind_host }}:{{ drawio_bind_port }}:8080"

networks: {}