name: "{{ home_name }}-my-exporter"
services:
  my_exporter:
    image: "{{ home_images.my_exporter.image }}"
    container_name: "{{ home_name }}-my-exporter"
    restart: always
    ports:
      - "{{ my_exporter_bind_host }}:{{ my_exporter_bind_port }}:8000/tcp"
    environment:
      TZ: "{{ home_timezone }}"
    command:
      - "uv"
      - "run" 
      - "src/main.py"
      - "--config=/config.yaml"
    
    volumes:
      - "{{ push_target_dir }}/config.yaml:/config.yaml:ro"
      - my_exporter_data:/data
networks: {}
volumes:
  my_exporter_data: {{ service_vars.volumes.my_exporter_data }}