- import_playbook: push-service.yml
  vars:
    service: fluentd
  tags:
    - fluentd
    - required

- import_playbook: wait-service.yml
  vars:
    service: fluentd # 等待各个机器上的fluentd服务启动
    service_host: "{{ fluentd_bind_host }}"
    service_port: "{{ fluentd_bind_port }}"
  tags:
    - fluentd
    - required

- import_playbook: push-service.yml
  vars:
    service: mosdns
  tags:
    - mosdns
    - required

- import_playbook: push-service.yml
  vars:
    service: nginx
  tags:
    - nginx
    - required

- import_playbook: push-service.yml
  vars:
    service: portainer
  tags:
    - portainer
    - required

- import_playbook: push-service.yml
  vars:
    service: node_exporter
  tags:
    - node_exporter

- import_playbook: push-service.yml
  vars:
    service: cadvisor
  tags:
    - cadvisor

- import_playbook: push-service.yml
  vars:
    service: grafana
  tags:
    - grafana

- import_playbook: push-service.yml
  vars:
    service: prometheus
  tags:
    - prometheus

- import_playbook: push-service.yml
  vars:
    service: samba
  tags:
    - samba

- import_playbook: push-service.yml
  vars:
    service: aria2
  tags:
    - aria2

- import_playbook: push-service.yml
  vars:
    service: acme_sh
  tags:
    - acme_sh

- import_playbook: push-service.yml
  vars:
    service: immich
  tags:
    - immich

- import_playbook: push-service.yml
  vars:
    service: drawio
  tags:
    - drawio

- import_playbook: push-service.yml
  vars:
    service: plantuml
  tags:
    - plantuml

- import_playbook: push-service.yml
  vars:
    service: speedtest
  tags:
    - speedtest

- import_playbook: push-service.yml
  vars:
    service: vaultwarden
  tags:
    - vaultwarden

- import_playbook: push-service.yml
  vars:
    service: gitea
  tags:
    - gitea

- import_playbook: push-service.yml
  vars:
    service: kms
  tags:
    - kms

- import_playbook: push-service.yml
  vars:
    service: homepage
  tags:
    - homepage

- import_playbook: push-service.yml
  vars:
    service: dify
  tags:
    - dify

- import_playbook: push-service.yml
  vars:
    service: tailscale
  tags:
    - tailscale

- import_playbook: push-service.yml
  vars:
    service: process_exporter
  tags:
    - process_exporter

- import_playbook: push-service.yml
  vars:
    service: my_exporter
  tags:
    - my_exporter

- import_playbook: push-service.yml
  vars:
    service: rclone
  tags:
    - rclone

- import_playbook: push-service.yml
  vars:
    service: alertmanager
  tags:
    - alertmanager

- import_playbook: push-service.yml
  vars:
    service: filebrowser
  tags:
    - filebrowser

- import_playbook: push-service.yml
  vars:
    service: dlna_render
  tags:
    - dlna_render

- import_playbook: push-service.yml
  vars:
    service: vfs_framework
  tags:
    - vfs_framework

- import_playbook: push-service.yml
  vars:
    service: it_tools
  tags:
    - it_tools