- import_playbook: push-service.yml
  vars:
    service: fluentd

- import_playbook: wait-service.yml
  vars:
    service: fluentd # 等待各个机器上的fluentd服务启动
    service_host: "{{ fluentd_bind_host }}"
    service_port: "{{ fluentd_bind_port }}"
  
- import_playbook: push-service.yml
  vars:
    service: mosdns

- import_playbook: push-service.yml
  vars:
    service: nginx
  tags:
    - nginx

- import_playbook: push-service.yml
  vars:
    service: portainer

- import_playbook: push-service.yml
  vars:
    service: node_exporter

- import_playbook: push-service.yml
  vars:
    service: cadvisor

- import_playbook: push-service.yml
  vars:
    service: prometheus

- import_playbook: push-service.yml
  vars:
    service: samba

- import_playbook: push-service.yml
  vars:
    service: aria2

- import_playbook: push-service.yml
  vars:
    service: acme_sh

- import_playbook: push-service.yml
  vars:
    service: immich

- import_playbook: push-service.yml
  vars:
    service: drawio

- import_playbook: push-service.yml
  vars:
    service: speedtest

- import_playbook: push-service.yml
  vars:
    service: vaultwarden