# 全局配置
global:
  # 抓取时间周期，默认为1分钟，这里设置为15s
  scrape_interval: 15s
  # eval的时间周期，默认为1分钟，用于计算规则，触发告警等操作
  evaluation_interval: 15s

# 告警规则配置
rule_files:
  - "/rules/*.rules"

# 各个服务抓取配置
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: # 自身指标
          - "{{ prometheus_bind_host }}:{{ prometheus_bind_port }}"
